databases:
  - name: money_track
    databaseName: money_track
    user: money_track

services:
  - type: web
    name: money_track
    runtime: ruby
    buildCommand: "./render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: money_track
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
